# SPDX-FileCopyrightText: Outscale SAS <opensource@outscale.com>
#
# SPDX-License-Identifier: BSD-3-Clause

version = 1

[[annotations]]
path = ["sdk/**", "k8s/**", ".github/**"]
SPDX-FileCopyrightText = "2025 Outscale SAS <opensource@outscale.com>"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["**.md", ".gitignore"]
SPDX-FileCopyrightText = "2025 Outscale SAS <opensource@outscale.com>"
SPDX-License-Identifier = "CC-BY-4.0"
