name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "*/go.*"
      - ".github/workflows/build.yml"
    
permissions:
  contents: read

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
    - name: â¬‡ï¸ Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
    - name: ğŸ” Reuse check
      run: |
        docker run --rm --volume $PWD:/data fsfe/reuse:5.1 lint
  sdk:
    runs-on: [self-hosted, linux]
    steps:
    - name: â¬‡ï¸ Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
    - name: â¬‡ï¸ Install Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
      with:
        go-version: '1.25'
    - name: 
      run: echo "replace github.com/outscale/goutils/sdk => ../sdk" >> k8s/go.mod
    - name: ğŸ” golangci-lint
      uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9
      with:
        version: v2.7.1
        working-directory: sdk
        args: --timeout=300s
        only-new-issues: true
    - name: ğŸ§ª Unit tests
      run: cd sdk && go test ./...
  k8s:
    runs-on: ubuntu-latest
    steps:
    - name: â¬‡ï¸ Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
    - name: â¬‡ï¸ Install Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
      with:
        go-version: '1.25'
    - name: ğŸ” golangci-lint
      uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9
      with:
        version: v2.7.1
        working-directory: k8s
        args: --timeout=300s
        only-new-issues: true
    - name: ğŸ§ª Unit tests
      run: cd k8s && go test ./...
