name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "*/go.*"
      - ".github/workflows/build.yml"
    
permissions:
  contents: read

jobs:
  sdk:
    runs-on: ubuntu-latest
    steps:
    - name: â¬‡ï¸ Checkout
      uses: actions/checkout@v5
    - name: â¬‡ï¸ Install Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'
    - name: ğŸ” golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.7.1
        working-directory: sdk
        args: --timeout=300s
        only-new-issues: true
    - name: ğŸ§ª Unit tests
      run: cd sdk && go test ./...
  k8s:
    runs-on: ubuntu-latest
    steps:
    - name: â¬‡ï¸ Checkout
      uses: actions/checkout@v5
    - name: â¬‡ï¸ Install Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'
    - name: ğŸ” golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.7.1
        working-directory: k8s
        args: --timeout=300s
        only-new-issues: true
    - name: ğŸ§ª Unit tests
      run: cd k8s && go test ./...
